config/routes.rb
Rails.application.routes.draw do
  root "students#new"
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'students#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :students, except: [:destroy]
  delete 'students/:id', to: 'students#destroy', as: 'delete_student'
  resources :students do
    resources :studentinfos
  end
  resources :students do
    resources :results, except: [:update, :destroy]
  end
  post 'students/:student_id/results/:id', to: 'results#update', as: 'edit_result'
  post 'students/:id/studentinfos/new', to: 'studentinfos#create', as: 'create_student'
  delete 'students/:id/results/:id', to: 'results#destroy', as: 'delete_result'
  get 'students/index'
  # post 'new' => 'studentinfo/:id/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result.rb
class Result < ApplicationRecord
    belongs_to :student

    validates :subjects, presence: true
    validates :gread, presence: true
end

app/models/student.rb
class Student < ApplicationRecord
  has_secure_password

  has_one :studentinfo, dependent: :destroy
  has_many :results, dependent: :destroy

  validates :email, presence: true, uniqueness: true,
                            format: { with: /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/, message: "Email invalid"  },
                            length: { minimum: 4, maximum: 254 }

  
end

app/models/studentinfo.rb
class Studentinfo < ApplicationRecord

  belongs_to :student

  validates :name, presence: true
  validates_each :name do |record, attr, value|
    record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
  end
  validates :address, presence: true
  validates :phoneNo, presence: true
  validates :gender, presence: true  
  
  validate :validate_dob

  def validate_dob
    if dob.present? && dob > DateTime.now
        errors.add(:dob, 'dob cant be in future')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?
  def current_user
    if session[:student_id]
      @current_user ||= Student.find(session[:student_id])
    else
      @current_user = nil
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @student = Student.find(params[:student_id])
    @results = @student.results.all
  end

  def show
    # @student = Student.find(params[:student_id])
    # @result = @student.results
  end

  def new
    @result = Result.new
  end

  def create
    @student = Student.find(params[:student_id])
    @result = @student.results.create(studentinfo_params)
    @result.save
    respond_to do |format|
      format.js 
      format.html { redirect_to student_results_path(@student)}
    end
  end
  
  def edit
    @result = Result.find(params[:id])
  end
  
  def update
    @result = Result.find(params[:id])
    @student = @result.student
    @result.student_id = @student.id

    if @result.update(studentinfo_params)
      redirect_to student_results_path
    else
      render :edit
    end
  end
  
  def destroy
    @student = Student.find(params[:student_id])
    @result = Result.find(params[:id])
    @result.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to @student, flash[:notice] = "deleted"}
    end
    # byebug
    # @result = Result.find(params[:id])
    # @result.destroy
    # redirect_to student_result_path(@student)
    # flash[:notice] = "deleted"    
  end
  
  private 
  def studentinfo_params
    params.require(:result).permit(:subjects, :gread, :id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    @student = Student.find_by_email(params[:email])
    if @student && @student.authenticate(params[:password])
      session[:student_id] = @student.id
      redirect_to @student , notice: "logged in"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end
  def destroy
    session[:student_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/studentinfos_controller.rb
class StudentinfosController < ApplicationController
  def index
    # @studentinfo = Studentinfo.find(params[:student_id])
    # @studentinfos = Studentinfo.all
  end

  def show
    @student = Student.find(params[:student_id])
    @studentinfo = @student.studentinfo
  end

  def new
    @studentinfo = Studentinfo.new
    @studentinfo.student = Student.find(params[:student_id])
  end

  def create
    @student = Student.find(params[:id])
    @studentinfo = @student.create_studentinfo(studentinfo_params)
    if @studentinfo.save
      redirect_to student_path(@student)
    else
      render 'new'
    end
  end
  
  def edit
    @studentinfo = Studentinfo.find(params[:id])
  end
  
  def update
    @studentinfo = Studentinfo.find(params[:id])
    @student = @studentinfo.student
    @studentinfo.student_id = @student.id
  
    if @studentinfo.update(studentinfo_params)
      redirect_to student_studentinfo_path
    else
      render :edit
    end
  end
  
  def destroy
    @studentinfo = Studentinfo.find(params[:student_id])
    @studentinfo.destroy
    redirect_to student_path
  end
  
  private 
  def studentinfo_params
    params.require(:studentinfo).permit(:name, :dob, :parentemail, :address, :education, :permanentaddress, :phoneNo, :gender, :address, :id, :student_id)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def edit
    @student = Student.find(params[:id])
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to new_student_studentinfo_path(@student), notice: "Student was successfully created." 
    else
      render :new
    end
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
        redirect_to @student, notice: "Student was successfully updated." 
    else
        render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to root_path, notice: "Student was successfully destroyed." 
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:email, :password, :password_confirmation, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/studentinfo_helper.rb
module StudentinfoHelper
end

app/helpers/studentinfos_helper.rb
module StudentinfosHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniProj</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
  <body>
  
  <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/results/_form.html.erb
<div class="border">
<%= form_for @result,remote: true, url: student_results_path do |form| %>
  <%= form.label :subject %>
  <div class="box">
    <%= form.text_field :subjects %>
  </div><br>

  <%= form.label :gread %>
  <div class="box">
    <%= form.text_field :gread %>
  </div>

  <div class="button">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/results/_result.html.erb
  <tr>
    <td><%= result.subjects %></td>
    <td colspan="15"></td>
    <td><%= result.gread %></td>
    <td colspan="15"></td>
    <td><%= link_to 'Edit', edit_student_result_path(id: result.id, student_id: result.student_id) %></td>
    <td><%= link_to 'destroy', delete_result_path(id: result.id, student_id: result.student_id), method: :delete, data: {confirm: 'Are you sure?', remote: true}, class: "delete" %></td>
  </tr>

app/views/results/create.js.erb
$('#new-result form').remove();
$('#new-result a').show()
$('table#bands tbody').append("<%= j render @result %>")

app/views/results/destroy.js.erb
$('.delete').bind('ajax:success', function() {
  $(this).closest('tr').fadeOut();
});

app/views/results/edit.html.erb
<h1>Result Info</h1>

<%= form_with model: @result, url: edit_result_path(id: @result.id, student_id: @result.student_id), method: :post do |form| %>
  <div>
    <%= form.label :subject %><br>
    <%= form.text_field :subjects %>
  </div>

  <div>
    <%= form.label :gread %><br>
    <%= form.text_field :gread %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<ul>
<%= link_to 'Back', student_results_path(id: @result.id, student_id: @result.student_id) %> 
  </ul>

  

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Result</h1>

<table id="bands">
  <thead>
    <tr>
      <th>Subject</th>
      <th colspan="15"></th>
      <th>Gread</th>
    </tr>
  </thead>

  <tbody>
  <%= render partial: 'result', collection: @results%>
  </tbody>
</table>

<br>

<div id="new-result">
<%= link_to "add student's result", new_student_result_path(@student), remote: true%><br>
</div>
<%= link_to 'Back to homepage', student_path(params[:student_id]) %>

app/views/results/new.html.erb
<h1>Result Info</h1>

<%= render 'form', result: @result %>

app/views/results/new.js.erb
$('#new-result a').parent().html("<%= j render 'form'%>")

app/views/results/show.html.erb
<%= form_with model: @results, url: student_result_path do |form| %>
  <div>
    <%= form.label :subject %><br>
    <%= form.text_field :subjects %>
  </div>

  <div>
    <%= form.label :gread %><br>
    <%= form.text_area :gread %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>  
<li><%= link_to 'destroy', delete_result_path(id: @results.id, student_id: @results.student_id), method: :delete, data: {confirm: 'Are you sure?', remote: true}, class: "delete" %>
<ul>
<%= link_to 'Back', student_path(params[:id]) %> 
  </ul>
  

app/views/studentinfos/_form.html.erb
<%= form_with model: @studentinfo, url: new_student_studentinfo_path(student_id: @studentinfo.student.id), method: 'post' do |form| %>

  <div>
  <br>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @studentinfo.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
  <br>
    <%= form.label :date_of_birth %><br>
    <%= form.date_field :dob %>
    <% @studentinfo.errors.full_messages_for(:dob).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
  <br>
    <%= form.label :parentemail %><br>
    <%= form.text_field :parentemail %>
    <% @studentinfo.errors.full_messages_for(:parentemail).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>


  <div>
  <br>
    <%= form.label :address %><br>
    <%= form.text_area :address %><br>
    <% @studentinfo.errors.full_messages_for(:address).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
  <br>
    <%= form.label :permenentaddress %><br>
    <%= form.text_area :permenentaddress %><br>
    <% @studentinfo.errors.full_messages_for(:permenentaddress).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  
  <div>
  </br>
  <%= form.radio_button :gender, "Female" %>
  <%= form.label :female %>
  <%= form.radio_button :gender, "Male" %>
  <%= form.label :male %>
  <%= form.radio_button :gender, "Other" %>
  <%= form.label :other %>
  <% @studentinfo.errors.full_messages_for(:gender).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>

  <div>
  <br>
    <%= form.label :Phone_Number %><br>
    
    <%= form.telephone_field :phoneNo %>
    <% @studentinfo.errors.full_messages_for(:phoneNo).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
  <br>
    <%= form.label :Current_Sem %><br>
    <%= form.select :education, ['Sem 1', 'Sem 2']%>
  </div>

  <div>
  <br>
    <%= form.submit %>
  </div>
  
<% end %>

app/views/studentinfos/edit.html.erb
<h1>Student Info</h1>

<%= form_with model: @studentinfo, url: student_studentinfo_path do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/studentinfos/index.html.erb
<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to 'logout', logout_path %>
<% else %>
  <%= link_to 'signup', signup_path %> or 
  <%= link_to 'login', login_path %>
<% end %>
<p id=”notice”><%= notice %></p>
<h1>Example</h1>

app/views/studentinfos/new.html.erb
<h1>Student Info</h1>

<%= render 'form', studentinfo: @studentinfo %>

app/views/studentinfos/show.html.erb
  
<h1>Student Info</h1>

<%= form_with model: @studentinfo, url: student_studentinfo_path do |form| %>

  <div>
  <br>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
  <br>
    <%= form.label :date_of_birth %><br>
    <%= form.date_field :dob %>
  </div>

  <div>
  <br>
    <%= form.label :parentemail %><br>
    <%= form.text_field :parentemail %>
  </div>


  <div>
  <br>
    <%= form.label :address %><br>
    <%= form.text_area :address %><br>
  </div>

  <div>
    
  <div>
  </br>
  <%= form.radio_button :gender, "Female" %>
  <%= form.label :female %>
  <%= form.radio_button :gender, "Male" %>
  <%= form.label :male %>
  <%= form.radio_button :gender, "Other" %>
  <%= form.label :other %>
  </div>

  <div>
  <br>
    <%= form.label :Phone_Number %><br>
    
    <%= form.telephone_field :phoneNo %>
  </div>

  <div>
  <br>
    <%= form.label :Current_Sem %><br>
    <%= form.select :education, ['Sem 1', 'Sem 2']%>
  </div>
  
<% end %>

<ul>
<%= link_to 'Edit Information', edit_student_studentinfo_path(@student) %> <br>
<%= link_to 'Back', student_path(params[:id]) %> 
  </ul>

app/views/students/_form.html.erb
<div class="container">
<h1 text="center">Signup</h1>
<%= form_with(model: student) do |form| %>
  
  <label for="staticEmail" class="col-sm-2 col-form-label">Email</label>
  <div class="col-sm-0">
    <%= form.text_field :email, placeholder: "Email" %>
  </div>
  <% student.errors.full_messages_for(:email).each do |message| %>
  <div><%= message %></div>
  <% end %>  
  
  <label for="inputPassword" class="col-sm-2 col-form-label">Password</label>
  <div class="col-sm-0">
    <%= form.password_field :password, placeholder: "Password" %>
  </div>
  <% student.errors.full_messages_for(:password).each do |message| %>
  <div><%= message %></div>
  <% end %>

  <label for="inputPassword" class="col-sm-2 col-form-label">Password Confirmation </label>
  <div class="col-sm-0">
    <%= form.password_field :password_confirmation, placeholder: "Password" %>
  </div>
  <% student.errors.full_messages_for(:password_confirmation).each do |message| %>
  <div><%= message %></div>
  <% end %>
  
  <div class="btn">
    <%= form.submit %>
  </div>
<% end %>

already have account?<%= link_to 'login', 'login' %>

</div>

app/views/students/edit.html.erb
<h1>Edit password</h1>
<%= @student.email %>

<%= form_with(model: @student) do |form| %>    
  
    <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password %>
      <% @student.errors.full_messages_for(:password).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div class="field">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
      <% @student.errors.full_messages_for(:password).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  
<%= link_to 'Back', @student %>

app/views/students/index.html.erb
# <p id="notice"><%= notice %></p>

#   <% if current_user %>
#   Logged in as <%= current_user.email %>.
#   <p id="notice"><%= notice %></p>
#   <strong>Email:</strong>
#   <%= current_user.email %>
#   </p>
#   <%= link_to 'Edit', edit_student_path(@student) %> |
#   <%= link_to 'Back', students_path %> |
#   <%= link_to 'logout', logout_path %></p>
  
#   <% else %>
#   <%= link_to 'signup', signup_path %>
#    <% end %>
# <p id=”notice”><%= notice %></p>

app/views/students/new.html.erb
<div class="bg-img">


<%= render 'form', student: @student %>

</div>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>  
<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<%= link_to 'Edit Password', edit_student_path(@student) %> <br>
<%= link_to 'logout', logout_path %> <br>
<%= link_to 'show student_information', student_studentinfo_path(@student) %><br>
<%= link_to 'result show', student_results_path(@student) %><br>